### ISSUE TITLE
No CPU information present for Asus PRIME X470-PRO with Ryzen R5  2600x

### ISSUE THREAD

**Issue by rombert** [groeck/lm-sensors#104]
I've just upgraded to the platform mentioned in $SUBJECT and get no CPU temperature and fan speed settings.

`$ sudo sensors-detect` does not detect any sensors:

```
# sensors-detect revision 6284 (2015-05-31 14:00:33 +0200)
# Board: ASUSTeK COMPUTER INC. PRIME X470-PRO
# Kernel: 4.16.6-1-default x86_64
# Processor: AMD Ryzen 5 2600X Six-Core Processor (23/8/2)

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): 
Module cpuid loaded successfully.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 16h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Intel digital thermal sensor...                             No
Intel AMB FB-DIMM thermal sensor...                         No
Intel 5500/5520/X58 thermal sensor...                       No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No
```

After running through the detection all I get is

```
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +39.8°C  (high = +70.0°C)

asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM
```

**Comment by groeck** [comment]
First of all, please remember that sensors-detect just detects hardware. It does not magically add drivers for the hardware it detects into the kernel.
Second, you are not running the latest version of sensors-detect; otherwise you would see "Family 17h" output above. You are running the latest (or a recent) version of the k10temp driver, though, which is good.
Third, the output is incomplete. It is at least somewhat unlikely that there is no Super-IO chip on this board. The output also does not provide any value, since the k10temp driver _does_ detect and support the CPU. Please provide complete output.

**Comment by rombert** [comment]
Thanks for the info @groeck . Regarding the version - is there a patch or set of patches that I should apply on top of 3.4.0 to include the 'Family 17h' checks? I see that 3.4.0 is marked as the latest release on GitHub.

I've also uploaded the full output, please see [sensors-x470.txt](https://github.com/groeck/lm-sensors/files/1984289/sensors-x470.txt)

**Comment by groeck** [comment]
There is no recent release; a new release would require cleaning up old links and references, and no one has time and/or enough interest to do that. You would have to run the top-of-tree version.
The output shows that your system has an IT8665 Super-IO chip. You would have to install the it87 driver available here to get support for it.

**Comment by groeck** [comment]
I don't have a task list. Just check out the repository and look for stale links/references.

it87 - two reasons:
- Bringing the upstream driver to the same level would require a large number of patches (one logical change per patch), and I don't have the time to do that.
- Even if I had the time, it would be all but impossible to find code reviewers, meaning I would have to push the changes into the upstream kernel without code reviews. While I am forced to do that on a regular basis, due to the lack of reviewers, this is just a bit too much.

**Comment by groeck** [comment]
Nothing to do for the lm-sensors package. Note that the it87 driver at https://github.com/groeck/it87 will be removed by August 1, 2018.

**Comment by jranke** [comment]
Thanks for all your work on it87 anyways! It still works for me on 4.16, but I guess I will have to learn to live without on 4.17.
